function( cmaketools_aux_source_directory )
    cmake_parse_arguments( ARG "NO_DOXYGEN" "DIRECTORY;OUT_VAR" "" ${ARGN} )
    aux_source_directory( ${ARG_DIRECTORY} sources_var )
    if( NOT ARG_NO_DOXYGEN )
        cmaketools_add_doxygen_input( ${ARG_DIRECTORY} )
    endif()
    list( APPEND ${ARG_OUT_VAR} ${sources_var} )
    set( ${ARG_OUT_VAR} ${${ARG_OUT_VAR}} PARENT_SCOPE )
endfunction()