function( cmaketools_add_test )
    cmake_parse_arguments( ARG "" "NAME;FILE;REGEX_PASS;REGEX_FAIL" "INCLUDE_DIRECTORIES;COMPILE_FLAGS;LINK_LIBRARIES;TEST_ARGS;ENVIRONMENT" ${ARGN} )
    # build the test executable
    add_executable( test_${ARG_NAME} ${ARG_FILE} )
    if( ARG_COMPILE_FLAGS )
        set_target_properties( test_${ARG_NAME} PROPERTIES COMPILE_FLAGS ${ARG_COMPILE_FLAGS} )
    endif()
    if(ARG_LINK_LIBRARIES)
        target_link_libraries( test_${ARG_NAME} ${ARG_LINK_LIBRARIES} )
    endif()
    target_include_directories( test_${ARG_NAME} PUBLIC inc ${ARG_INCLUDE_DIRECTORIES} )
    set_target_properties( test_${ARG_NAME} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/tests" )
    # add the unit test
    add_test( NAME t_${test_name} COMMAND ${CMAKE_BINARY_DIR}/tests/test_${ARG_NAME} ${ARG_TEST_ARGS} )
    if( NOT "${ARG_REGEX_PASS}" STREQUAL "" )
        set_tests_properties( t_${test_name} PROPERTIES PASS_REGULAR_EXPRESSION "${ARG_REGEX_PASS}" )
    endif()
    if( NOT "${ARG_REGEX_FAIL}" STREQUAL "" )
        set_tests_properties( t_${test_name} PROPERTIES FAIL_REGULAR_EXPRESSION "${ARG_REGEX_FAIL}" )
    endif()
    if( ARG_ENVIRONMENT )
        set_tests_properties( t_${test_name} PROPERTIES ENVIRONMENT ${ARG_ENVIRONMENT} )
    endif()
endfunction()