function( cmaketools_print_env _namespace )
    get_property( EVARS GLOBAL PROPERTY ${_namespace}_ALL_VARS )
    if( EVARS )
        message( STATUS "** Imported environment variables (${_namespace}) **" )
        foreach( evar ${EVARS} )
            get_property( EVAR GLOBAL PROPERTY ${_namespace}_${evar} )
            message( STATUS " -> ${evar}=${EVAR}"  )
        endforeach()
        message( STATUS "************************************" )
    endif()
endfunction()